deploy-to-vercel:
  stage: deploy
  image: node:16.16.0

  variables: 
    PREVIEW_URL: https://$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG.rivi-frontend-js.vercel.app

  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == 'main'

  environment:
    name: vercel/$CI_COMMIT_REF_NAME
    url: https://$PREVIEW_URL

  script:
    - npm i -g vercel
    - DEPLOYMENT_URL=$(vercel --name $CI_PROJECT_NAME --confirm -t WBdBDqanVNRyiFeF4XmyEkS3 --scope rivi-frontend-js)
    - vercel alias set $DEPLOYMENT_URL $PREVIEW_URL -t WBdBDqanVNRyiFeF4XmyEkS3 --scope rivi-frontend-js
